title = "Datagen"

[lang]
#Way the program reads from language files.
#'i' means it will automatically read from the internet.
#'d' means it will automatically download the files.
#'a' means it will ask every time the program needs the language files.
read = "a"

[errors]
logErrors = true #Decides wether the error should be logged.
showExeptions = false #Decides wether the exeption should be shown in the console. (Better for debugging)
